baseURL: https://subsystemcoding.github.io/
languageCode: en-us
title: SubsytemCoding Team
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: false # To allow you to write raw html in your md files, change to True

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/sp.PNG
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Play. Explore. Meet.
    # Hero subtitle (optional)
    subtitle: We are ready to serve you differently. Striving towards being the number one social media platform, by engaging users in unique and competetive games and providing a secure environment to interact. Our group has an aim to perfect ourselves through learning about user- requiremenets in more detail, so we can improvise our functionalities through careful observation.
    
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://subsystemcoding.github.io/socialpixel/"
    # Hero image (from static/images/___)
    image: illustrations/giraffe.svg # https://www.flaticon.com/free-icon/giraffe_2991365?term=wildlife&page=1&position=91&page=1&position=91&related_id=2991365&origin=search
    # this is for the dogs playing:  <span>Photo by <a href="https://unsplash.com/@invisibleman_photography?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">David Taffet</a> on <a href="https://unsplash.com/s/photos/pets?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: /
  - title: Download
    url: https://subsystemcoding.github.io/socialpixel/
  - title: Support
    sublinks:
    - title: Documentation
      url: /
    - title: FAQs
      url: /
    - title: Customer Service
      url: /
    - title: Privacy Policy
      url: https://socialpixel.s3.me-south-1.amazonaws.com/privacy.html
    - title: Terms and Conditions
      url: https://socialpixel.s3.me-south-1.amazonaws.com/terms.html
  - title: Log in
    url: /
  - title: Sign up
    url: /
    button: true
  section1:
    title: Together, Let's Discover
    subtitle: A New World.
    tiles:
    - title: Share
      icon: share # https://www.flaticon.com/free-icon/share_4091538?term=share&page=1&position=66&page=1&position=66&related_id=4091538&origin=search
      text: Like and Share all the wonders you see. Start to scroll through the posts and channels created by us to help improve communication and sightseeing virtually.
      url: /
      buttonText: Try it Out!
    - title: Chat to Play
      icon: chat # https://www.flaticon.com/free-icon/feedback_4110142?term=chat&page=1&position=65&page=1&position=65&related_id=4110142&origin=search
      text: Chat with fellow animal lovers and arrange play dates! This is a function created to help users connect and explore the various screens.
      url: /
      buttonText: Get Started
    - title: Play Games
      icon: game # https://www.flaticon.com/free-icon/game-console_1083364?term=game&related_id=1083364
      text: Join us to play games about your four-legged friends! The game is developed in accordance to the specifications and needs of the consumers. Discover our map and channels screen to view the nearby images, find them and get rewarded.
      url: /
      buttonText: Game On!
  section2:
    title: The One and Only interactive app which is developed by SubsystemCoding 
    subtitle: For the World Outside
    features:
    - title: Our Vision
      text: To have an ideal browsing and interaction experience with any screen size, platform, or orientation, we use sensitive web design concepts. The main purpose of our project was to develop a platform that largely helps educators to make decisions after viewing details, students to realize how wonderful the world around them is, organizations or photographers to present their work or advertise, and the working class to just relax and play games to take a break. We have tested and analysed each functionality before presenting it. We intend to improvise in the future
      # https://docs.microsoft.com/en-us/power-platform/admin/about-unified-interface
      # Icon (from /images/illustrations/icons/___.svg)
      icon: u-inter # https://www.flaticon.com/free-icon/responsive_1055687?term=interface&page=1&position=17&page=1&position=17&related_id=1055687&origin=search
    # - title: Cross-device synchronisation
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: doc-sync
    # - title: Nomad system
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: mobile-feed
  section3:
    title: One Platform 
    subtitle: All Devices
    image: illustrations/mockup/phone.gif
    buttonText: Let's Get Started
    buttonLink: "#"
  section4:
    title: Our Group Members Include
    subtitle: Mohammed Ashab Uddin, Benjamin Jacob Reji, Anas Patel, Riya Koshy, Prithyuksha Viswanathan, Jerome Joji, Mohammed Boush		
    clients:
    - 
      quote: We enjoyed contributing towards this project as it is for a good cause.
      job: Team Member
      img: man
    - 
      quote: We use this app everyday. We were able to complete this due to our motivation and communication.
      job: Team Mmeber
      img: woman
    - 
      quote: We are proud to create this platform. We were able to guide my fellow team members and make everything work sucessfully.
      job: Team Leader
      img: man
    
 # https://www.flaticon.com/free-icon/woman_2922561?term=women&related_id=2922561
    
    
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: logos/sp.PNG
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    # Icons are from Font Awesome
    - link: https://github.com/subsystemcoding
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blogs"
        links:
        - text: Latest news
          link: /
        - text: Tech articles
          link: /
